### PR TITLE
Replace pyfit-sne with opentsne to support OSX, and clean up tutorial notebook

### PR DESCRIPTION
**Pull request by mzhu22**
Main change is the move to `openTSNE`:
- `openTSNE` has comparable performance to `pyfit-sne`, but it's better-maintained and has multiplatform support, whereas `pyfit-sne` only works on Linux.
- I made a separate `environment_osx` file, since `faiss-gpu` also only supports Linux, but we want to keep that one for performance reasons.

Minor changes:
- I fixed up some broken sections of the tutorial notebook as I went through it
- A bunch of formatting changes got applied since I have VSCode set up to autoformat as I save. That's just based on my personal setup, but I can set up project-configs later on

### CODE REVIEW

**Review by joshuahwu — COMMENTED** [review]
Looks pretty good. Can you change it so that instead of specifying `method == openTSNE`, it remains `method == fitsne`? Fitsne is the name of the optimization algorithm which is implemented, so I'd like to continue to referencing that when running analyses.

**Comment by mzhu22** [comment]
> Looks pretty good. Couple of things.
> 
> 1. Can you change it so that instead of specifying `method == openTSNE`, it remains `method == fitsne`? Fitsne is the name of the optimization algorithm which is implemented, so I'd like to continue to referencing that when running analyses.
> 2. Is input data type the same as the output?
> 3. Is there a difference in speed?

1. sounds good
2. do you mean for the openTSNE embedding? looks like output is a `TSNEEmbedding` object that's a subclass of `ndarray` (with some additional metadata like the affinities and params used in the optimization).
3. openTSNE has some benchmarks up https://opentsne.readthedocs.io/en/stable/benchmarks.html. It looks like it's slower than raw `fitsne`, but it blames that on "python overhead" so I imagine it's about the same as `pyfit-sne`

**Review by joshuahwu — APPROVED** [review]

**Comment by joshuahwu** [comment]
> 1. sounds good
> 2. do you mean for the openTSNE embedding? looks like output is a `TSNEEmbedding` object that's a subclass of `ndarray` (with some additional metadata like the affinities and params used in the optimization). https://github.com/pavlin-policar/openTSNE/blob/994cf0be15f7363733a17cf93c578c8d0b4e125a/openTSNE/tsne.py#L403
> 3. openTSNE has some benchmarks up https://opentsne.readthedocs.io/en/stable/benchmarks.html. It looks like on 1 core, it's slower than raw C++ `fitsne`, but it blames that on "python runtime overhead" so I imagine it's about the same as `pyfit-sne`. On 8 cores it's the same as `fitsne`

Cool thanks.
2. Sorry, I meant that usually we work w/float32 np arrays. So wondering if that is retained.

**Comment by mzhu22** [comment]
Ohhh. Looks like they convert to float64: https://github.com/pavlin-policar/openTSNE/blob/994cf0be15f7363733a17cf93c578c8d0b4e125a/openTSNE/tsne.py#L512C9-L512C12.

Should we convert back to 32?

**Comment by mzhu22** [comment]
I imagine it's the reduce memory usage?

**Comment by mzhu22** [comment]
>Another thing we should check. Some packages run into speed issues if you don't feed them float64 for some reason.

Based on reading the openTSNE code, I think this one accepts anything. But I think it'll be easier to understand the dappy code if we explicitly convert to float64 before tsne and and then convert back after. I'll do that later

**Pull request merged**
